_commit: 6658bed
_src_path: /Users/kschaper/Monarch/kozahub/koza-ingest-template
copyright_year: '2026'
email: info@monarchinitiative.org
full_name: Monarch Initiative
github_handle: monarch-initiative
github_org: monarch-initiative
license: MIT
project_description: BioGRID ingest for gene-to-gene interactions using MITAB format
    data.
project_name: biogrid-ingest
project_slug: biogrid_ingest
